### ISSUE TITLE
pandalist会导致qq邮箱app拉取不到gmail的邮件

### ISSUE THREAD

**Issue by panpando** [BurpSuite/UPlus-PandaList#1]
是pandadns的问题还是配置的问题？

**Comment by BurpSuite** [comment]
哈，都猜到了啊，是他的问题，不是我的问题，所有的都走DIRECT

**Comment by BurpSuite** [comment]
我还以为不会有人猜到PandaDNS呢😁

**Comment by panpando** [comment]
那我去pandadns那去问问

**Comment by BurpSuite** [comment]
解决方法:暂时部分规则改为Proxy，让那些规则走国内服务器，或者通过SKIP解决，过两天重新写一下国内的部分，

**Comment by BurpSuite** [comment]
嗯

**Comment by panpando** [comment]
火箭里没设置代理的话改成proxy能连上吗？取消强制dns有没有用？

**Comment by BurpSuite** [comment]
我指的设置代理，让那部分异常的规则走代理，取消了强制DNS那不就是普通规则了嘛

**Comment by BurpSuite** [comment]
怎么说呢，有利有弊吧

**Comment by panpando** [comment]
把火箭关掉立马就能下载app和拉取邮件了，估计把子域名取消强制dns有用

**Comment by BurpSuite** [comment]
把子域名取消DNS，GEOIP还是会判断走DNS，即使把子域名和GEOIP都取消掉，还是按照PandaDNS走DIRECT

**Comment by BurpSuite** [comment]
关掉当然不会出现

**Comment by panpando** [comment]
折腾了一下午还是搞不定，用回hosts了

**Comment by BurpSuite** [comment]
其实本来就是一个很简单的事，之前也和你说了，把那些出问题的规则改成Proxy，加个国内代理，因为是他(PandaDNS)并不归我管，所以我无法解决，我最多能解决的就是1.把那个出问题的加个Proxy让他走国内代理服务器2.把那些出问题的转化成SKIP让他跳过

**Comment by BurpSuite** [comment]
所以说有利有弊吧，非常简单的一个简易DNS规则，不需要更新什么HOSTS，而且HOSTS也看不了YouTube，HOSTS也存在被指向恶意IP的风险，容易导致账号被盗等。不过随便吧，怎么样都行，我仅仅是出个规则，和规则维护。如果还有什么问题可以继续追问，如果没有什么问题的话点一下"Close"即可，谢谢。

**Comment by panpando** [comment]
明白你的意思，只是不想加代理而已，另外排查域名也很费功夫，还是谢谢哈

**Comment by panpando** [comment]
https://github.com/cnAnonymous/hosts
这个hosts可以看yt和play下app，我自己修改了一点

**Comment by BurpSuite** [comment]
嗯
